theme: jekyll-theme-cayman
title: AVZ-Status
description: Errechnet dir wie viele Einsatztage/AVZ du tagesaktuell bereits hast, noch vor dir liegen (bis Out) und es insgesamt sind (In bis Out).

Der AVZ lässt sich in allen aktuellen AVZ-Stufen (Stufe 1 – 6) auswählen und errechnet diesen in Tagen.
Ein Widget wird auch angeboten, dass euch schnell darüber informiert wie viel ihr bereits verdient habt, wie viel Tage/Wochen noch verbleiben und natürlich den Fortschritt in Prozent.
Zudem bietet dir die App eine echte Motivation! Sie zeigt dir deinen Einsatzfortschritt nicht nur in Prozent, sondern auch optisch. Dazu kannst du selbst entscheiden, was dich am meisten motiviert und das als Motivationsbild festlegen.
Des Weiteren gibt es eine Urlaubsfunktion, in dieser können Sie bis zu 30 Tage festlegen, an diesen kein AVZ berechnet werden soll.

AVZ-Status ist eine reine offline App, die somit keine Internetverbindung benötigt und nur dem privaten Zweck dient. Alle vom Nutzer eingegebenen Daten werden ausschließlich auf dem vom Nutzer eigenen Gerät gespeichert, verarbeitet und können zu keinem Zeitpunkt über eine Internetverbindung abgerufen werden.
